projectTitle: "DROP: Detection of RNA Outliers Pipeline"
sampleAnnotation: sample_annotation.tsv
genomeAssembly: hg19

aberrantExpression:
    run: true
    groups:
        - group1
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 0.05
    zScoreCutoff: 0
    genesToTest: null
    maxTestedDimensionProportion: 3
    yieldSize: 2000000

aberrantSplicing:
    run: true
    groups:
        - group1
    recount: false
    longRead: false
    keepNonStandardChrs: false
    filter: true
    minExpressionInOneSample: 20
    quantileMinExpression: 10
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 0.1
    maxTestedDimensionProportion: 6
    genesToTest: null
    FRASER_version: "FRASER"
    deltaPsiCutoff: 0.3
    quantileForFiltering: 0.95

mae:
    run: false
    groups:
        - group1

rnaVariantCalling:
    run: false
    groups:
        - group1

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools
